### ISSUE TITLE
Tracking issue: requirements for 0.20.0 alpha release

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#1102]
- [x] Handling #925 
- [x] The ForwardDemesGraph post-init relies on a mix of `np.rint` and rust's `f64::round()` that is fragile. The quickest fix here is to make sure our Python back-end mimics "round to even". A slightly more difficult path is to add this feature to upstream and/or our internal rust wrapper, then getting the result back into Python.
- [x] The idea of "total simulation length" should come from the ForwardDemesGraph itself and not from mucking around in Python.
- [x] Remove `examples/discrete_demography/*.py`
- [x] Remove `doc/examples/IM.md` and others related to discrete_demography

**Comment by molpopgen** [comment]
Done as of #1118
