### ISSUE TITLE
Final TODO list for 0.5.1

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#290]
- [x] Update change log to reflect PRs
- [x] Add docs for features introduced in #275
- [x] Add docs for features introduced in #279 
- [x] Add docs for features introduced in #272
