### ISSUE TITLE
demes-related docs issue tracker

### ISSUE THREAD

**Issue by molpopgen** [molpopgen/fwdpy11#718]
Things to document:

- [x] How to use the model metadata to initialize a DiploidPopulation
- [x] How to get the names/ids of the demes that exist at the end of a simulation.
- [x] How to handle "selfing" vis-a-vis standard W-F assumption.
      (One usually will want to disable residual selfing.)
